<?php

namespace App\Traits;

trait HasJournalArticles
{
    public function journalArticles()
    {
        return [
            [
                'title'     => 'Who is … Jermaine',
                'imageLink' => 'https://hyperfocus.cc/wp-content/uploads/2024/07/DSC08036-2000x1334.jpg',
                'body'      => "Who is Jermaine?\n\nHey, I am Jermaine, 24 years old and freshly graduated from my Communication Design studies. My mother is from South Korea and Christian, my dad is from Ghana and Muslim. I live here in Hamburg, Germany, and I'm trying to be myself to the fullest extent.\n\nWhat are you doing here and tell us who you really are?\n\nI’m a Junior Designer at Hyperfocus, diving into the world of design with passion and curiosity. Who am I? A creative who loves making things, whether it's design, music, photography, or fashion.\n\nHow did you come to work with Hyperfocus?\n\nAfter finishing my studies, I was eager to find a space that matched my creative vision. My mentor, Alexander Meinhardt, highly recommended Hyperfocus. After a few inspiring chats with the team at one of his events, it felt like the perfect fit. The energy and dedication here is infectious, and I feel honored to join.\n\nWhat made you fall in love with design?\n\nMy passion for design ignited with my first job at a textile printing company. Seeing digital designs come to life was exciting — as it turned ideas into something tangible.\n\nWhat's your style?\n\nIt is my aim to refine my style as I go. I love experimenting with edgy textures and striking contrasts. I tend to create a solid foundation for my designs, then add a visual provocation.\n\nYou working on anything big in the background?\n\nMusic, especially producing beats, is my biggest hobby alongside design. I hope to upgrade my home studio step by step and connect with more artists.\n\nDo you have any design heroes?\n\nIf I’d have to pick, Kanye West. He's rightfully controversial, but his impact as a producer, rapper, fashion designer, and artist is undeniable. He has always inspired me with his versatility, showing that you don't have to limit yourself to one interest but can excel in multiple disciplines as a creative. His influence on music, fashion, and culture has truly motivated me. But oftentimes when I get inspired, it’s the work that stands out to me.\n\nInspire a new generation of designers in one word.\n\nStrive / Dedication"
            ],
            [
                'title'     => 'ADC – Artificial Realities 2023',
                'imageLink' => 'https://hyperfocus.cc/wp-content/uploads/2023/11/ADC-ArtificalRealities-Paul-Watmough-Halim-stage-2000x1323.jpg',
                'body'      => "It was a big day for us.\n\nOur co-founder Paul stood on stage this year at ADC – Artificial Realities in Düsseldorf, Germany and hosted a panel of two incredible guests, Iskra Velichkova (Kleinanzeigen) & Roger Dudler (Frontify). They were welcomed by a packed auditorium of attendees eager to hear something new and exciting about AI in branding.\n\nWe can safely say the talk did not disappoint. An honest and emotional discussion lit the room with energy and intrigue. Iskra’s perspective was powerful, while Roger brought both fears and optimism for AI’s future. It was a wonderful honour and experience for us to represent our studio and these amazing people.\n\nA big thank you to the Art Directors Club (ADC) and to Burkhard Müller for inviting us."
            ],
            [
                'title'     => 'Who is … Giang?',
                'imageLink' => 'https://hyperfocus.cc/wp-content/uploads/2024/02/Gydient_HakoHangul.gif',
                'body'      => "Who is Giang?\n\nI'm Tra Giang Nguyen, a creative thinker known as Gydient. I value clarity, so when I stepped into the creative industry, I inked ‘NO BULLSHIT’ on my left arm.\n\nWhat are you doing here and tell us who you really are?\n\nI’m joining Hyper as a design director, and I’m eager to contribute my sharp skills in building brand design concepts, delivering only top‑notch design, and creating a multidisciplinary toolkit with a strong design direction.\n\nBesides, I love brands and products that display intelligent, witty creativity. Being creative means tackling old problems with a fresh approach. It could be in daily life, business, or play.\n\nHow did you come to work with Hyperfocus?\n\nOne sunny day, I dropped by the office, had a chat with the team, and everything just clicked. Hyperfocus aiming to be the top design studio? I'm excited to be part of building that goal.\n\nWhat's your style?\n\nPoetic & witty.\n\nYou working on anything big in the background?\n\nOn weekdays, I'm all about learning and growing with the Hyperfocus team. On weekends, I dedicate time to sharing lessons from my experiences via a channel broadcast—part of my routine for my upcoming book, expected in 2025.\n\nWhat made you fall in love with design?\n\nThe power to change communication.\n\nDo you have any design heroes?\n\nFirst is Paula Scher; her design is poetic but efficient. Second is Stefan Sagmeister because I want to be brave but smart.\n\nInspire a new generation of designers in one word.\n\nNO BULLSHIT"
            ],
            [
                'title'     => 'RedDot Award',
                'imageLink' => 'https://hyperfocus.cc/wp-content/uploads/2023/08/RedDot-award-Heimplanet-article.jpg',
                'body'      => "This one is quite special! We won the prestigious RedDot award for our work with Heimplanet. We have had a relationship with them in various guises for the past couple of years. This award is kind of an accumulation of that, but the work that was judged was from a recent brand refresh. We undertook the task of reworking the foundations of the brand that we had already created.\n\nBuilding on those foundations, we reimagined the whole design system, organised the fundamentals, created a new tone of voice, and made sense of the brand. A big clean‑up and a razor‑sharp brand platform was built to unify the entire team.\n\nThe RedDot stands for innovation and design at the highest standard. Many products, people, and projects that have inspired us as creatives have been awarded the RedDot, so this is quite the celebration for Hyperfocus. Super chuffed 🙂\n\nWatch the video: https://www.youtube.com/watch?v=ErT3jbQ6SZs&t=130s"
            ],
        ];
    }
}
